# Generated by Django 4.0 on 2022-01-21 13:21

import django.core.validators
from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(default=tickets.models.generate_reservation_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('swimlane', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('client_type', models.CharField(choices=[('private_client', 'Private client'), ('swim_school', 'Swim school')], default='private_client', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
